image: docker

services:
  - docker:dind

before_script:
  - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
  script:
    - docker pull registry.gitlab.com/mrwindowsd/devops-skillbox || true
    - docker build -t registry.gitlab.com/mrwindowsd/devops-skillbox:latest -t registry.gitlab.com/mrwindowsd/devops-skillbox:$CI_COMMIT_SHORT_SHA . --cache-from registry.gitlab.com/mrwindowsd/devops-skillbox
    - docker push registry.gitlab.com/mrwindowsd/devops-skillbox:latest
    - docker push registry.gitlab.com/mrwindowsd/devops-skillbox:$CI_COMMIT_SHORT_SHA
